# services/dockerfile
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

# Копируем csproj файлы
COPY LogServer.Core/*.csproj LogServer.Core/
COPY LogServer.Infrastructure/*.csproj LogServer.Infrastructure/
COPY LogServer.Host/*.csproj LogServer.Host/

# Восстанавливаем зависимости
RUN dotnet restore LogServer.Host/LogServer.Host.csproj

# Копируем весь код
COPY . .

# Собираем
WORKDIR /src/LogServer.Host
RUN dotnet publish -c Release -o /app/publish

# Финальный образ
FROM mcr.microsoft.com/dotnet/runtime:9.0
WORKDIR /app

# Создаём папку для логов
RUN mkdir -p /app/logs

# Копируем бинарники
COPY --from=build /app/publish .

# Открываем порт
EXPOSE 9000

# Точка входа
ENTRYPOINT ["dotnet", "LogServer.Host.dll"]